package bibliotecaantonioestebanaguero.Vistas;



import bibliotecaantonioestebanaguero.AccesoADatos.LibroData;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import bibliotecaantonioestebanaguero.entidades.Libro;

public class AltaLibro1 extends javax.swing.JPanel {

    private LibroData libData = new LibroData();
    private Libro lib = new Libro();
    private Libro libroActual = null;


//    boolean isEdition = false;
//    com.mycompany.models.Users userEdition;

    public AltaLibro1() {
        initComponents();
        
    }



    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        jTidIsbn = new javax.swing.JTextField();
        apPLbl = new javax.swing.JLabel();
        jTtitulo = new javax.swing.JTextField();
        apMLbl = new javax.swing.JLabel();
        jTautor = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        domLbl = new javax.swing.JLabel();
        jTanio = new javax.swing.JTextField();
        NUEVO = new javax.swing.JButton();
        phoneLbl = new javax.swing.JLabel();
        jTeditorial = new javax.swing.JTextField();
        jTgenero = new javax.swing.JTextField();
        phoneLbl1 = new javax.swing.JLabel();
        BUSCAR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CheckBoxESTADO = new javax.swing.JCheckBox();
        GUARDAR = new javax.swing.JButton();
        BORRAR = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        title.setText("Registrar nuevo Libro");

        nameLbl.setText("ID ISBN");

        jTidIsbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTidIsbnKeyTyped(evt);
            }
        });

        apPLbl.setText("TITULO");

        jTtitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTtituloKeyTyped(evt);
            }
        });

        apMLbl.setText("AUTOR");

        jTautor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTautorKeyTyped(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));

        domLbl.setText("AÑO");

        jTanio.setToolTipText("");
        jTanio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTanioKeyTyped(evt);
            }
        });

        NUEVO.setBackground(new java.awt.Color(0, 0, 0));
        NUEVO.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NUEVO.setForeground(new java.awt.Color(255, 255, 255));
        NUEVO.setText("NUEVO");
        NUEVO.setBorderPainted(false);
        NUEVO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NUEVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUEVOActionPerformed(evt);
            }
        });

        phoneLbl.setText("GENERO");

        jTeditorial.setToolTipText("");
        jTeditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTeditorialActionPerformed(evt);
            }
        });

        jTgenero.setToolTipText("");
        jTgenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTgeneroActionPerformed(evt);
            }
        });
        jTgenero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTgeneroKeyReleased(evt);
            }
        });

        phoneLbl1.setText("EDITORIAL");

        BUSCAR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BUSCAR.setText("Buscar");
        BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSCARActionPerformed(evt);
            }
        });

        jLabel1.setText("ESTADO");

        GUARDAR.setBackground(new java.awt.Color(0, 0, 0));
        GUARDAR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        GUARDAR.setForeground(new java.awt.Color(255, 255, 255));
        GUARDAR.setText("GUARDAR");
        GUARDAR.setBorderPainted(false);
        GUARDAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUARDARActionPerformed(evt);
            }
        });

        BORRAR.setBackground(new java.awt.Color(0, 0, 0));
        BORRAR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BORRAR.setForeground(new java.awt.Color(255, 255, 255));
        BORRAR.setText("BORRAR");
        BORRAR.setBorderPainted(false);
        BORRAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BORRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BORRARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(553, 553, 553))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(nameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(223, 223, 223))
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(apPLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(182, 182, 182))
                                    .addComponent(jTtitulo)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(apMLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(180, 180, 180))
                                    .addComponent(jTautor))
                                .addGap(68, 68, 68))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(jTidIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(79, 79, 79)
                                        .addComponent(BUSCAR))
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(CheckBoxESTADO))
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(NUEVO, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(GUARDAR, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTanio)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(domLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(220, 220, 220))
                                    .addComponent(jTeditorial)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(phoneLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(218, 218, 218))
                                    .addComponent(jTgenero))
                                .addGap(72, 72, 72))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BORRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(244, 244, 244))))))
            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bgLayout.createSequentialGroup()
                    .addGap(436, 436, 436)
                    .addComponent(phoneLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(71, Short.MAX_VALUE)))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(nameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTidIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(apPLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(apMLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTautor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(CheckBoxESTADO))
                        .addGap(31, 31, 31)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NUEVO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GUARDAR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(domLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTanio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phoneLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTgenero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jTeditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(BORRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26))))
            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bgLayout.createSequentialGroup()
                    .addGap(191, 191, 191)
                    .addComponent(phoneLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(220, 220, 220)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NUEVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUEVOActionPerformed
 
        limpiarCampos();
        libroActual = null;

        
        
        
    }//GEN-LAST:event_NUEVOActionPerformed

    private void jTeditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTeditorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTeditorialActionPerformed

    private void jTgeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTgeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTgeneroActionPerformed

    private void BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSCARActionPerformed
         try {
            Integer isbn = Integer.parseInt(jTidIsbn.getText());
            libroActual = libData.buscarLibroPorIdLibro(isbn);
            if (libroActual != null) {
                jTtitulo.setText(libroActual.getTitulo().toLowerCase());
                jTautor.setText(libroActual.getAutor().toLowerCase());
                jTanio.setText(libroActual.getAnio() + "");
                jTgenero.setText(libroActual.getGenero().toLowerCase());
                jTeditorial.setText(libroActual.getEditorial().toLowerCase());
                CheckBoxESTADO.setSelected(libroActual.isEstado());

            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un numero de ID ISBN válido. ");
        }
    }//GEN-LAST:event_BUSCARActionPerformed

    private void GUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUARDARActionPerformed
        // TODO add your handling code here:
     try {
            Integer isbn = Integer.parseInt(jTidIsbn.getText());
            String titulo = jTtitulo.getText().toLowerCase();
            String autor = jTautor.getText().toLowerCase();
            int anio = Integer.parseInt(jTanio.getText()+"");
            String genero = jTgenero.getText().toLowerCase();
            String editorial = jTeditorial.getText().toLowerCase();
            Boolean estado = CheckBoxESTADO.isSelected();
            
            
        if (titulo.isEmpty() || autor.isEmpty() || genero.isEmpty() || editorial.isEmpty())  {
             JOptionPane.showMessageDialog(this, "No pueden existir campos vacíos.");
                  
                return;
      }

            if (libroActual == null) {

                libroActual = new Libro(titulo, autor, anio, genero, editorial, estado);
                libData.guardarLibro(libroActual);

            } else {
                libroActual.setIsbn(isbn);
                libroActual.setTitulo(titulo);
                libroActual.setAutor(autor);
                libroActual.setAnio(anio);
                libroActual.setGenero(genero);
                libroActual.setEditorial(editorial);
                libroActual.setEstado(true);
                libData.modificarLibro(lib);
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un numero de ISBN válido. ");
        }

    }//GEN-LAST:event_GUARDARActionPerformed

    private void BORRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BORRARActionPerformed
        // TODO add your handling code here:
         if (libroActual != null) {
            //  int isbn=0;
            libData.eliminarLibroLogico(libroActual.getIsbn());
            libroActual = null;
            limpiarCampos();

        } else {
            JOptionPane.showMessageDialog(this, "No hay un Libro seleccionado. ");
        }
    }//GEN-LAST:event_BORRARActionPerformed

    private void jTidIsbnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTidIsbnKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
    boolean numero = key >= '0' && key <= '9';
    
    if (!numero) {
        evt.consume();
        JOptionPane.showMessageDialog(this, "Solo se aceptan números naturales.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    if (jTidIsbn.getText().trim().length() == 10) {
        evt.consume();
        JOptionPane.showMessageDialog(this, "El ISBN no debe exceder los 10 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jTidIsbnKeyTyped

    private void jTtituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTtituloKeyTyped
        // TODO add your handling code here:
          // Verifica si el carácter no es una letra ni un espacio en blanco
    if (!(Character.isLetter(evt.getKeyChar())) && !(evt.getKeyChar() == KeyEvent.VK_SPACE)) {
        evt.consume(); // Consume el carácter no válido
        // Muestra el mensaje de error solo una vez
        JOptionPane.showMessageDialog(this, "Solo se aceptan letras para introducir el nombre del Titulo del libro.", "Error", JOptionPane.ERROR_MESSAGE); 
    }
    }//GEN-LAST:event_jTtituloKeyTyped

    private void jTautorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTautorKeyTyped
        // TODO add your handling code here:
         // Verifica si el carácter no es una letra ni un espacio en blanco
    if (!(Character.isLetter(evt.getKeyChar())) && !(evt.getKeyChar() == KeyEvent.VK_SPACE)) {
        evt.consume(); // Consume el carácter no válido
        // Muestra el mensaje de error solo una vez
        JOptionPane.showMessageDialog(this, "Solo se aceptan letras para introducir el nombre del Autor del libro.", "Error", JOptionPane.ERROR_MESSAGE); 
    }
         
    }//GEN-LAST:event_jTautorKeyTyped

    private void jTgeneroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTgeneroKeyReleased
        // TODO add your handling code here:
// Verifica si el carácter no es una letra ni un espacio en blanco
    if (!(Character.isLetter(evt.getKeyChar())) && !(evt.getKeyChar() == KeyEvent.VK_SPACE)) {
        evt.consume(); // Consume el carácter no válido
        // Muestra el mensaje de error solo una vez
        JOptionPane.showMessageDialog(this, "Solo se aceptan letras para introducir el Genero del libro.", "Error", JOptionPane.ERROR_MESSAGE); 
    }

    }//GEN-LAST:event_jTgeneroKeyReleased

    private void jTanioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTanioKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
    boolean numero = key >= '0' && key <= '9';
    
    if (!numero) {
        evt.consume();
        JOptionPane.showMessageDialog(this, "Solo se aceptan números naturales.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    if (jTanio.getText().trim().length() == 4) {
        evt.consume();
        JOptionPane.showMessageDialog(this, "El AÑO no debe exceder los 4 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jTanioKeyTyped


    
    private void limpiarCampos() {
        jTidIsbn.setText("");
        jTtitulo.setText("");
        jTanio.setText("");
        jTautor.setText("");
        jTeditorial.setText("");
        jTgenero.setText("");
        CheckBoxESTADO.setSelected(true);

    }
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BORRAR;
    private javax.swing.JButton BUSCAR;
    private javax.swing.JCheckBox CheckBoxESTADO;
    private javax.swing.JButton GUARDAR;
    private javax.swing.JButton NUEVO;
    private javax.swing.JLabel apMLbl;
    private javax.swing.JLabel apPLbl;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel domLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTanio;
    private javax.swing.JTextField jTautor;
    private javax.swing.JTextField jTeditorial;
    private javax.swing.JTextField jTgenero;
    private javax.swing.JTextField jTidIsbn;
    private javax.swing.JTextField jTtitulo;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JLabel phoneLbl1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}