/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bibliotecaantonioestebanaguero.Vistas;


import bibliotecaantonioestebanaguero.AccesoADatos.EjemplarData;
import bibliotecaantonioestebanaguero.AccesoADatos.LectorData;
import bibliotecaantonioestebanaguero.AccesoADatos.LibroData;
import bibliotecaantonioestebanaguero.AccesoADatos.PrestamoData;
import bibliotecaantonioestebanaguero.AccesoADatos.RellenarCombos;
import bibliotecaantonioestebanaguero.Utilidades.CustomRendererAutor;
import bibliotecaantonioestebanaguero.entidades.Libro;
import bibliotecaantonioestebanaguero.entidades.Prestamo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Otras
 */
public class BusquedaAutor extends javax.swing.JPanel {

    private RowFilter<DefaultTableModel, Object> rowFilter;
    private TableRowSorter<DefaultTableModel> trs; // Declarar el TableRowSorter como una variable de instancia.
    private List<Prestamo> listP;
    private List<Libro> listaA;
    private List<Libro> listaL;
    private LibroData libData;
    private EjemplarData ejeData;
    private PrestamoData presData;
    private LectorData lecData;

    private DefaultTableModel modelo;

    RellenarCombos re = new RellenarCombos();

    /**
     * Creates new form Mision
     */
    public BusquedaAutor() {
        initComponents();

        libData = new LibroData();
        listaL = libData.listarLibro();
        modelo = new DefaultTableModel();
        re.RellenarComboBox("libro", "autor", jComboBox1);
        rowFilter = RowFilter.regexFilter("(?i)", 1);
        presData = new PrestamoData();
        ejeData = new EjemplarData();
        lecData = new LectorData();
        cargaLibros();
        //configurarTabla();
        armarCabeceraTabla();
        //armarCabeceraTabla();
      jComboBox1.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            String opcionSeleccionada = (String) jComboBox1.getSelectedItem();
            // Actualiza su tabla en función de la opción seleccionada
            actualizarTabla(opcionSeleccionada);
        }

    });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTgenero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTbusqueda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTisbn = new javax.swing.JTextField();
        jTtitulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTautor = new javax.swing.JTextField();
        jBeditar = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(774, 429));

        jTgenero.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FILTRO BUSQUEDA:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("BUSQUEDA RAPIDA:");

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBox1KeyReleased(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTbusqueda.setToolTipText("");
        jTbusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTbusquedaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTbusquedaKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("ID ISBN:");

        jTisbn.setToolTipText("");

        jTtitulo.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("TITULO:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("AUTOR:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("GENERO:");

        jTautor.setToolTipText("");

        jBeditar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBeditar.setText("EDITAR");
        jBeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeditarActionPerformed(evt);
            }
        });

        jBeliminar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBeliminar.setText("ELIMINAR");
        jBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(470, 470, 470)
                        .addComponent(jBeditar)
                        .addGap(27, 27, 27)
                        .addComponent(jBeliminar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel2)
                            .addGap(46, 46, 46)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTgenero, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addGap(0, 7, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTisbn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTautor, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jTisbn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTautor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTgenero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBeditar)
                    .addComponent(jBeliminar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBeditarActionPerformed

    private void jTbusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbusquedaKeyReleased
        // TODO add your handling code here:
        borrarFilas();
        String autor = null;

        for (Libro lib : libData.listarLibro()) {

            if (lib.getAutor().toLowerCase().startsWith(jTbusqueda.getText().toLowerCase())) {
                modelo.addRow(new Object[]{
                    lib.getIsbn(),
                    lib.getTitulo(),
                    lib.getAutor(),
                    lib.getAnio(),
                    lib.getGenero(),
                    lib.getEditorial(),
                    lib.isEstado(),});
            }
        }


    }//GEN-LAST:event_jTbusquedaKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int seleccion = jTable1.rowAtPoint(evt.getPoint());
        jTisbn.setText(String.valueOf(jTable1.getValueAt(seleccion, 0)));
        jTtitulo.setText(String.valueOf(jTable1.getValueAt(seleccion, 1)));
        jTautor.setText(String.valueOf(jTable1.getValueAt(seleccion, 2)));
        jTgenero.setText(String.valueOf(jTable1.getValueAt(seleccion, 4)));
    }//GEN-LAST:event_jTable1MouseClicked

    private void jBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBeliminarActionPerformed

    private void jTbusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbusquedaKeyTyped
        // TODO add your handling code here:
  borrarFilas();
        for (Libro lib : libData.listarLibro()) {

            if (lib.getAutor().toLowerCase().startsWith( jTbusqueda.getText().toLowerCase())) {
                modelo.addRow(new Object[]{
                    lib.getIsbn(),
                    lib.getTitulo(),
                    lib.getAutor(),
                    lib.getAnio(),
                    lib.getGenero(),
                    lib.getEditorial(),
                    lib.isEstado(),});
            }
        }     
    }//GEN-LAST:event_jTbusquedaKeyTyped

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:

    if (evt.getStateChange() == ItemEvent.SELECTED) {
        // Obtén la opción seleccionada en el JComboBox
        String opcionSeleccionada = (String) jComboBox1.getSelectedItem();
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); // Limpia la tabla antes de agregar los nuevos resultados.

        for (Libro lib : libData.listarLibro()) {
            if (opcionSeleccionada.equals("Todos") || lib.getAutor().toLowerCase().startsWith(opcionSeleccionada.toLowerCase())) {
                modelo.addRow(new Object[]{
                    lib.getIsbn(),
                    lib.getTitulo(),
                    lib.getAutor(),
                    lib.getAnio(),
                    lib.getGenero(),
                    lib.getEditorial(),
                    lib.isEstado()
                });
            }
        }

        jTable1.setModel(modelo);
    }

                   
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyReleased
        // TODO add your handling code here:
        
         // TODO add your handling code here:
        String autor = jTbusqueda.getText().toLowerCase();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); // Limpia la tabla antes de agregar los nuevos resultados.

        for (Libro lib : libData.listarLibro()) {
            if (lib.getAutor().toLowerCase().startsWith(autor)) {
                modelo.addRow(new Object[]{
                    lib.getIsbn(),
                    lib.getTitulo(),
                    lib.getAutor(),
                    lib.getAnio(),
                    lib.getGenero(),
                    lib.getEditorial(),
                    lib.isEstado()
                });
            }
        }

      jTable1.setModel(modelo);
                           

                           
    }//GEN-LAST:event_jComboBox1KeyReleased

    private void cargaLibros() {
        for (Libro lib : listaL) {
            jTable1.setModel(modelo);
        }
    }

    private void armarCabeceraTabla() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("ID ISBN");
        filaCabecera.add("Titulo");
        filaCabecera.add("Autor");
        filaCabecera.add("Año");
        filaCabecera.add("Genero");
        filaCabecera.add("Editorial");
        filaCabecera.add("Estado");

        for (Object it : filaCabecera) {
            modelo.addColumn(it);
        }

        jTable1.setModel(modelo);

        // Aplica el renderer personalizado a la columna "Autor"
        int columnaAutor = 2;
        jTable1.getColumnModel().getColumn(columnaAutor).setCellRenderer(new CustomRendererAutor());
    }

private void borrarFilas() {
    try {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        int filas = modelo.getRowCount();
        for (int f = filas - 1; f >= 0; f--) {
            modelo.removeRow(f);
        }
    } catch (NullPointerException ex) {
        JOptionPane.showMessageDialog(null, "Ocurrio un error: " + ex.getMessage());
    }
}

    private void obtenerTituloLibroSeleccionado(){
     LibroData libData=new LibroData();
    //borrarFilasTabla();
    Libro selec = (Libro) jComboBox1.getSelectedItem();
    List <Libro> lista = (List <Libro>) libData.buscarLibroPorIdLibro(selec.getIsbn());
       
    for(Libro libro: lista){
            modelo.addRow(new Object[] { libro.getIsbn(), libro.getTitulo(), libro.getAutor(), libro.getAnio(), libro.getGenero(), libro.getEditorial(), libro.isEstado()});
            System.out.println(libro.getTitulo());
    }
    }

    

   

   

private void actualizarTabla(String opcionSeleccionada) {
    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
    modelo.setRowCount(0); // Borra la tabla antes de agregar nuevos resultados.

    for (Libro lib : libData.listarLibro()) {
        if (opcionSeleccionada.equals("Todos") || lib.getAutor().toLowerCase().startsWith(opcionSeleccionada.toLowerCase())) {
            modelo.addRow(new Object[]{
                lib.getIsbn(),
                lib.getTitulo(),
                lib.getAutor(),
                lib.getAnio(),
                lib.getGenero(),
                lib.getEditorial(),
                lib.isEstado()
            });
        }
    }

    jTable1.setModel(modelo);
}








    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBeditar;
    private javax.swing.JButton jBeliminar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTautor;
    private javax.swing.JTextField jTbusqueda;
    private javax.swing.JTextField jTgenero;
    private javax.swing.JTextField jTisbn;
    private javax.swing.JTextField jTtitulo;
    // End of variables declaration//GEN-END:variables
}
