/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bibliotecaantonioestebanaguero.Vistas;


import bibliotecaantonioestebanaguero.AccesoADatos.LibroData;
import bibliotecaantonioestebanaguero.entidades.Libro;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import javax.swing.JOptionPane;


/**
 *
 * @author Antonio
 */
public class CargarLibros extends javax.swing.JPanel {
 private LibroData libData = new LibroData();
    private Libro lib = new Libro();
    private Libro libroActual = null;

    /**
     * Creates new form Principal
     */
    public CargarLibros() {
        initComponents();
     
    }
    
   
       
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTIsbn = new javax.swing.JTextField();
        jTtitulo = new javax.swing.JTextField();
        jTautor = new javax.swing.JTextField();
        jTanio = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTgenero = new javax.swing.JTextField();
        jTeditorial = new javax.swing.JTextField();
        jCheckBestado = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jBbuscar = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        bg.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Formulario Carga de Libros");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ID ISBN:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("TITULO:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("AUTOR:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("AÑO:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("GENERO:");

        jTIsbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTIsbnKeyTyped(evt);
            }
        });

        jTtitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTtituloKeyTyped(evt);
            }
        });

        jTautor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTautorKeyTyped(evt);
            }
        });

        jTanio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTanioKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("EDITORIAL:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("ESTADO:");

        jTgenero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTgeneroKeyTyped(evt);
            }
        });

        jTeditorial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTeditorialKeyTyped(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbibliotecanuevo/Imagenes/libroMagico4.jpg"))); // NOI18N

        jBbuscar.setBackground(new java.awt.Color(255, 255, 255));
        jBbuscar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBbuscar.setText("BUSCAR");
        jBbuscar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarActionPerformed(evt);
            }
        });

        jbNuevo.setBackground(new java.awt.Color(255, 255, 255));
        jbNuevo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbNuevo.setText("NUEVO");
        jbNuevo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jBEliminar.setBackground(new java.awt.Color(255, 255, 255));
        jBEliminar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBEliminar.setText("ELIMINAR");
        jBEliminar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBGuardar.setBackground(new java.awt.Color(255, 255, 255));
        jBGuardar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBGuardar.setText("GUARDAR");
        jBGuardar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                        .addGap(137, 137, 137))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBestado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(277, 277, 277))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jbNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40)
                        .addComponent(jBEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(41, 41, 41)
                        .addComponent(jBGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(264, 264, 264))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTIsbn)
                                .addGap(18, 18, 18)
                                .addComponent(jBbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(3, 3, 3)))
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTautor, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTanio, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                        .addComponent(jTgenero)
                                        .addComponent(jTeditorial)))))
                        .addGap(91, 91, 91)))
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(72, 72, 72))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBbuscar))
                        .addGap(17, 17, 17)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTautor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTgenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTeditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jCheckBestado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbNuevo)
                            .addComponent(jBEliminar)
                            .addComponent(jBGuardar))
                        .addGap(53, 53, 53))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarActionPerformed
        // TODO add your handling code here:
         try {
            Integer isbn = Integer.parseInt(jTIsbn.getText());
            libroActual = libData.buscarLibroPorIdLibro(isbn);
            if (libroActual != null) {
                jTtitulo.setText(libroActual.getTitulo().toLowerCase());
                jTautor.setText(libroActual.getAutor().toLowerCase());
                jTanio.setText(libroActual.getAnio() + "");
                jTgenero.setText(libroActual.getGenero().toLowerCase());
                jTeditorial.setText(libroActual.getEditorial().toLowerCase());
                jCheckBestado.setSelected(libroActual.isEstado());

            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un numero de ID ISBN válido. ");
        }


    }//GEN-LAST:event_jBbuscarActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        // TODO add your handling code here:
         limpiarCampos();
        libroActual = null;
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        // TODO add your handling code here:
        if (libroActual != null) {
            //  int isbn=0;
            libData.eliminarLibroLogico(libroActual.getIsbn());
            libroActual = null;
            limpiarCampos();

        } else {
            JOptionPane.showMessageDialog(this, "No hay un Libro seleccionado. ");
        }
                                            
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        // TODO add your handling code here:
       try {
    String isbnText = jTIsbn.getText();
    
    if (isbnText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "El número de ISBN es autoincremental y se generará automáticamente.");
        jTIsbn.setToolTipText("El número de ISBN es autoincremental y se generará automáticamente.");
        return; // Finaliza la ejecución de la función si el ISBN está vacío.
    }                    
    
        Integer isbn = Integer.parseInt(jTIsbn.getText());
        String titulo = jTtitulo.getText().toLowerCase();
        String autor = jTautor.getText().toLowerCase();
        int anio = Integer.parseInt(jTanio.getText()+"");
        String genero = jTgenero.getText().toLowerCase();
        String editorial = jTeditorial.getText().toLowerCase();
        Boolean estado = jCheckBestado.isSelected();

        if (titulo.isEmpty() || autor.isEmpty() || genero.isEmpty() || editorial.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No pueden existir campos vacíos.");
            return; // Finaliza la ejecución de la función si hay campos vacíos.
        }

        if (libroActual == null) {
            libroActual = new Libro(titulo, autor, anio, genero, editorial, estado);
            libData.guardarLibro(libroActual);
        } else {
            libroActual.setIsbn(isbn);
            libroActual.setTitulo(titulo);
            libroActual.setAutor(autor);
            libroActual.setAnio(anio);
            libroActual.setGenero(genero);
            libroActual.setEditorial(editorial);
            libroActual.setEstado(true);
            libData.modificarLibro(lib);
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Debe ingresar un número de ISBN válido.");
        // Muestra el ToolTip en caso de error de formato
        jTIsbn.setToolTipText("El número de ISBN es autoincremental y se generará automáticamente.");
        return; // Finaliza la ejecución de la función si hay un error de formato.
    
}

    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jTIsbnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTIsbnKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
    boolean numero = key >= '0' && key <= '9';
    
    if (!numero) {
        evt.consume();
        JOptionPane.showMessageDialog(this, "Solo se aceptan números naturales.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    if (jTIsbn.getText().trim().length() == 10) {
        evt.consume();
        JOptionPane.showMessageDialog(this, "El ISBN no debe exceder los 10 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_jTIsbnKeyTyped

    private void jTtituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTtituloKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTtituloKeyTyped

    private void jTautorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTautorKeyTyped
        // TODO add your handling code here:
           if (!(Character.isLetter(evt.getKeyChar())) && !(evt.getKeyChar() == KeyEvent.VK_SPACE)) {
        evt.consume(); // Consume el carácter no válido
        // Muestra el mensaje de error solo una vez
        JOptionPane.showMessageDialog(this, "Solo se aceptan letras para introducir el nombre del Autor.", "Error", JOptionPane.ERROR_MESSAGE); 
    }
    }//GEN-LAST:event_jTautorKeyTyped

    private void jTanioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTanioKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
    boolean numero = key >= '0' && key <= '9';
    
    if (!numero) {
        evt.consume();
        JOptionPane.showMessageDialog(this, "Solo se aceptan números naturales.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    if (jTanio.getText().trim().length() == 4) {
        evt.consume();
        JOptionPane.showMessageDialog(this, "El Año no debe exceder los 4 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jTanioKeyTyped

    private void jTgeneroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTgeneroKeyTyped
        // TODO add your handling code here:
         // Verifica si el carácter no es una letra ni un espacio en blanco
    if (!(Character.isLetter(evt.getKeyChar())) && !(evt.getKeyChar() == KeyEvent.VK_SPACE)) {
        evt.consume(); // Consume el carácter no válido
        // Muestra el mensaje de error solo una vez
        JOptionPane.showMessageDialog(this, "Solo se aceptan letras para introducir el genero del libro.", "Error", JOptionPane.ERROR_MESSAGE); 
    }
    }//GEN-LAST:event_jTgeneroKeyTyped

    private void jTeditorialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTeditorialKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTeditorialKeyTyped

private void limpiarCampos() {
        jTIsbn.setText("");
        jTtitulo.setText("");
        jTautor.setText("");
        jTanio.setText("");
        jTgenero.setText("");
        jTeditorial.setText("");
        jCheckBestado.setSelected(true);

    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBbuscar;
    private javax.swing.JCheckBox jCheckBestado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTIsbn;
    private javax.swing.JTextField jTanio;
    private javax.swing.JTextField jTautor;
    private javax.swing.JTextField jTeditorial;
    private javax.swing.JTextField jTgenero;
    private javax.swing.JTextField jTtitulo;
    private javax.swing.JButton jbNuevo;
    // End of variables declaration//GEN-END:variables
}
