package bibliotecaantonioestebanaguero.Vistas;


import bibliotecaantonioestebanaguero.AccesoADatos.EjemplarData;
import bibliotecaantonioestebanaguero.AccesoADatos.LectorData;
import bibliotecaantonioestebanaguero.AccesoADatos.LibroData;
import bibliotecaantonioestebanaguero.AccesoADatos.PrestamoData;
import bibliotecaantonioestebanaguero.AccesoADatos.RellenarCombos;
import bibliotecaantonioestebanaguero.Utilidades.CustomRenderer;
import bibliotecaantonioestebanaguero.entidades.Libro;
import bibliotecaantonioestebanaguero.entidades.Prestamo;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;

public class LibroPorTitulo extends javax.swing.JPanel {

    private List<Prestamo> listP;
    private List<Libro> listaL;
    private LibroData libData;
    private EjemplarData ejeData;
    private PrestamoData presData;
    private LectorData lecData;
private Libro lib = new Libro();
    private DefaultTableModel modelo;

    RellenarCombos re = new RellenarCombos();

    public LibroPorTitulo() {
        initComponents();

       
        
        
        
        libData = new LibroData();
        listaL = libData.listarLibro();
         modelo = new DefaultTableModel();
          re.RellenarComboBox("libro", "titulo", cBoxTitulo);
        DefaultTableModel modelo = new DefaultTableModel();
        JTable jtablaTitulo = new JTable(modelo);
       
        RowFilter<Object, Object> rowFilter = RowFilter.regexFilter("(?i)", 1);
        presData = new PrestamoData();
        ejeData = new EjemplarData();
        lecData = new LectorData();
        cargaLibros();
       // cargarCombo();
        armarCabeceraTabla();
       // borrarFilas();
         cBoxTitulo.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            String opcionSeleccionada = (String)  cBoxTitulo.getSelectedItem();
            // Actualiza su tabla en función de la opción seleccionada
            actualizarTabla(opcionSeleccionada);
        }

    });

    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTcampoBusqueda = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtablaTitulo = new javax.swing.JTable();
        cBoxTitulo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jBeditar = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();
        jTxtId = new javax.swing.JTextField();
        jTxtTitulo = new javax.swing.JTextField();
        jTxtAutor = new javax.swing.JTextField();
        jTxtanio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txteditorial = new javax.swing.JTextField();
        jTxtgenero = new javax.swing.JTextField();
        txtestado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FILTRO DE BUSQUEDA:");

        jTcampoBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTcampoBusquedaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTcampoBusquedaKeyTyped(evt);
            }
        });

        jtablaTitulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtablaTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablaTituloMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtablaTitulo);

        cBoxTitulo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cBoxTituloItemStateChanged(evt);
            }
        });
        cBoxTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cBoxTituloKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BUSQUEDA RAPIDA DEL LIBRO:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID ISBN:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TITULO:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("AUTOR:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("AÑO:");

        jBeditar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBeditar.setText("MODIFICAR");
        jBeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeditarActionPerformed(evt);
            }
        });

        jBeliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBeliminar.setText("ELIMINAR");
        jBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("GENERO:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("EDITORIAL:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ESTADO:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Autor:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("AÑO:");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(51, 51, 51))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cBoxTitulo, 0, 171, Short.MAX_VALUE)
                            .addComponent(jTcampoBusqueda)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                                .addComponent(jBeditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(44, 44, 44)
                                .addComponent(jBeliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(52, 52, 52))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtestado)
                                    .addComponent(txteditorial)
                                    .addComponent(jTxtgenero, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTxtanio)
                            .addComponent(jTxtAutor)
                            .addComponent(jTxtTitulo)
                            .addComponent(jTxtId))))
                .addContainerGap())
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTcampoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(14, 14, 14)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cBoxTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jTxtgenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addComponent(jLabel8))
                            .addComponent(txteditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBeditar)
                            .addComponent(jBeliminar))
                        .addGap(27, 27, 27))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTcampoBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTcampoBusquedaKeyReleased
        // TODO add your handling code here:
         borrarFilas();
        String titulo = null;
        
        for (Libro lib : libData.listarLibro()) {

            if (lib.getTitulo().toLowerCase().startsWith(jTcampoBusqueda.getText().toLowerCase())) {
                modelo.addRow(new Object[]{
                    lib.getIsbn(),
                    lib.getTitulo(),
                    lib.getAutor(),
                    lib.getAnio(),
                    lib.getGenero(),
                    lib.getEditorial(),
                    lib.isEstado(),});
            }
        }

    }//GEN-LAST:event_jTcampoBusquedaKeyReleased

    private void jtablaTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaTituloMouseClicked
        // TODO add your handling code here:
        int seleccion = jtablaTitulo.rowAtPoint(evt.getPoint());
        jTxtId.setText(String.valueOf(jtablaTitulo.getValueAt(seleccion, 0)));
        jTxtTitulo.setText(String.valueOf(jtablaTitulo.getValueAt(seleccion, 1)));
        jTxtAutor.setText(String.valueOf(jtablaTitulo.getValueAt(seleccion, 2)));
        jTxtanio.setText(String.valueOf(jtablaTitulo.getValueAt(seleccion, 3)));
        jTxtgenero.setText(String.valueOf(jtablaTitulo.getValueAt(seleccion, 4)));
        txteditorial.setText(String.valueOf(jtablaTitulo.getValueAt(seleccion, 5)));
        txtestado.setText(String.valueOf(jtablaTitulo.getValueAt(seleccion, 6)));
    }//GEN-LAST:event_jtablaTituloMouseClicked

    private void cBoxTituloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cBoxTituloItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
      
        String opcionSeleccionada = (String) cBoxTitulo.getSelectedItem();
        
        DefaultTableModel modelo = (DefaultTableModel) jtablaTitulo.getModel();
        modelo.setRowCount(0); // Limpia la tabla antes de agregar los nuevos resultados.

        for (Libro lib : libData.listarLibro()) {
            if (opcionSeleccionada.equals("Todos") || lib.getTitulo().toLowerCase().startsWith(opcionSeleccionada.toLowerCase())) {
                modelo.addRow(new Object[]{
                    lib.getIsbn(),
                    lib.getTitulo(),
                    lib.getAutor(),
                    lib.getAnio(),
                    lib.getGenero(),
                    lib.getEditorial(),
                    lib.isEstado()
                });
            }
        }

        jtablaTitulo.setModel(modelo);
    }

                                         
    }//GEN-LAST:event_cBoxTituloItemStateChanged
            
    private void cBoxTituloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cBoxTituloKeyReleased
        // TODO add your handling code here:
        String titulo = jTcampoBusqueda.getText().toLowerCase();
        DefaultTableModel modelo = (DefaultTableModel) jtablaTitulo.getModel();
        modelo.setRowCount(0); // Limpia la tabla antes de agregar los nuevos resultados.

        for (Libro lib : libData.listarLibro()) {
            if (lib.getAutor().toLowerCase().startsWith(titulo)) {
                modelo.addRow(new Object[]{
                    lib.getIsbn(),
                    lib.getTitulo(),
                    lib.getAutor(),
                    lib.getAnio(),
                    lib.getGenero(),
                    lib.getEditorial(),
                    lib.isEstado()
                });
            }
        }
    }//GEN-LAST:event_cBoxTituloKeyReleased

    private void jTcampoBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTcampoBusquedaKeyTyped
        // TODO add your handling code here:
       borrarFilas();
        for (Libro lib : libData.listarLibro()) {

            if (lib.getTitulo().toLowerCase().startsWith(jTcampoBusqueda.getText().toLowerCase())) {
                modelo.addRow(new Object[]{
                    lib.getIsbn(),
                    lib.getTitulo(),
                    lib.getAutor(),
                    lib.getAnio(),
                    lib.getGenero(),
                    lib.getEditorial(),
                    lib.isEstado(),});
            }
    }                            
    }//GEN-LAST:event_jTcampoBusquedaKeyTyped

    private void jBeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeditarActionPerformed
//    int filaSeleccionada = jtablaTitulo.getSelectedRow();
//
//    if (filaSeleccionada != -1) {
//        DefaultTableModel modelo = (DefaultTableModel) jtablaTitulo.getModel();
//
//        String id = jTxtId.getText();
//        String titulo = jTxtTitulo.getText();
//        String autor = jTxtAutor.getText();
//        String anio = jTxtanio.getText();
//        String genero = jTxtgenero.getText();
//        String editorial = txteditorial.getText();
//        String estado = txtestado.getText();
//
//        if (titulo.isEmpty() || autor.isEmpty() || genero.isEmpty() || editorial.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "No pueden existir campos vacíos.");
//            return; // Finaliza la ejecución de la función si hay campos vacíos.
//        }
//        Object libroActual = null;
//
//        if (libroActual == null) {
//            libroActual = new Libro(titulo, autor, anio, genero, editorial, estado);
//            libData.guardarLibro((Libro) libroActual);
//        } else {
//            try {
//                int isbn = Integer.parseInt(id);
//
//                libroActual.(isbn);
//                libroActual.setTitulo(titulo);
//                libroActual.setAutor(autor);
//                libroActual.setAnio(anio);
//                libroActual.setGenero(genero);
//                libroActual.setEditorial(editorial);
//                libroActual.setEstado(true);
//
//                libData.modificarLibro(libroActual);
//            } catch (NumberFormatException ex) {
//                JOptionPane.showMessageDialog(this, "Debe ingresar un número de ISBN válido.");
//                // Muestra el ToolTip en caso de error de formato
//                jTxtId.setToolTipText("El número de ISBN es autoincremental y se generará automáticamente.");
//                return; // Finaliza la ejecución de la función si hay un error de formato.
//            }
//        }
//
//        // Limpia los campos de texto después de la modificación
//        jTxtId.setText("");
//        jTxtTitulo.setText("");
//        jTxtAutor.setText("");
//        jTxtanio.setText("");
//        jTxtgenero.setText("");
//        txteditorial.setText("");
//        txtestado.setText("");
//
//        // Añade aquí la lógica para actualizar tus datos subyacentes, si es necesario.
//    } else {
//        JOptionPane.showMessageDialog(this, "Selecciona una fila para modificar.");
//    }
//

    }//GEN-LAST:event_jBeditarActionPerformed

    
    private void jBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBeliminarActionPerformed
  
    private void cargaLibros() {
        for (Libro libro : listaL) {
            jtablaTitulo.setModel(modelo);
        }
    }


    private void armarCabeceraTabla() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("ID ISBN");
        filaCabecera.add("Titulo");
        filaCabecera.add("Autor");
        filaCabecera.add("Año");
        filaCabecera.add("Genero");
        filaCabecera.add("Editorial");
        filaCabecera.add("Estado");

        for (Object it : filaCabecera) {
            modelo.addColumn(it);
            
        }

        jtablaTitulo.setModel(modelo);

        // Aplica el renderer personalizado a la columna "ID ISBN"
        int columnaTitulo = 1;
        jtablaTitulo.getColumnModel().getColumn(columnaTitulo).setCellRenderer(new CustomRenderer());
    }

   private void borrarFilas() {
    try {
        DefaultTableModel modelo = (DefaultTableModel) jtablaTitulo.getModel();
        int filas = modelo.getRowCount();
        for (int f = filas - 1; f >= 0; f--) {
            modelo.removeRow(f);
        }
    } catch (NullPointerException ex) {
        JOptionPane.showMessageDialog(null, "Ocurrio un error: " + ex.getMessage());
    }
}

 
private void actualizarTabla(String opcionSeleccionada) {
    DefaultTableModel modelo = (DefaultTableModel) jtablaTitulo.getModel();
    modelo.setRowCount(0); // Borra la tabla antes de agregar nuevos resultados.

    for (Libro lib : libData.listarLibro()) {
        if (opcionSeleccionada.equals("Todos") || lib.getTitulo().toLowerCase().startsWith(opcionSeleccionada.toLowerCase())) {
            modelo.addRow(new Object[]{
                lib.getIsbn(),
                lib.getTitulo(),
                lib.getAutor(),
                lib.getAnio(),
                lib.getGenero(),
                lib.getEditorial(),
                lib.isEstado()
            });
        }
    }

    jtablaTitulo.setModel(modelo);
}


 private void limpiarCampos() {
        jTxtId.setText("");
        jTxtTitulo.setText("");
        jTxtAutor.setText("");
        jTxtanio.setText("");
        jTxtgenero.setText("");
      txteditorial.setText("");
       txtestado.setText("");

    }
        
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JComboBox<String> cBoxTitulo;
    private javax.swing.JButton jBeditar;
    private javax.swing.JButton jBeliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTcampoBusqueda;
    private javax.swing.JTextField jTxtAutor;
    private javax.swing.JTextField jTxtId;
    private javax.swing.JTextField jTxtTitulo;
    private javax.swing.JTextField jTxtanio;
    private javax.swing.JTextField jTxtgenero;
    private javax.swing.JTable jtablaTitulo;
    private javax.swing.JTextField txteditorial;
    private javax.swing.JTextField txtestado;
    // End of variables declaration//GEN-END:variables

    private void cargarCombo() {
        re.RellenarComboBox("libro", "titulo", cBoxTitulo);
    }
}
